# Numpy Exercises 

Now that we've learned about Numpy let's test your knowledge. 

#### Import Numpy as np

In [2]:
import numpy as np


#### Create an array of 10 zeros 

In [3]:
zeros_array = np.zeros(10)

In [4]:
print("Array of 10 zeros:\n", zeros_array)

Array of 10 zeros:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [6]:
ones_array = np.ones(10)

In [7]:
print("Array of 10 ones:\n", ones_array)

Array of 10 ones:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [12]:
fires_array = np.full(10,5)

In [13]:
print("Array of 10 fives:\n", fires_array)

Array of 10 fives:
 [5 5 5 5 5 5 5 5 5 5]


#### Create an array of the integers from 10 to 50

In [14]:
array_10_to_50 = np.arange(10, 51)

In [15]:
print("Array of integers from 10 to 50:\n", array_10_to_50)

Array of integers from 10 to 50:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [16]:
even_array = np.arange(10, 51, 2)

In [17]:
print("Array of even integers from 10 to 50:\n", even_array)

Array of even integers from 10 to 50:
 [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create an array of all the odd integers from 10 to 50

In [20]:
odd_array = np.arange(11, 51, 2)

In [21]:
print("Array of odd integers from 10 to 50:\n", odd_array)

Array of odd integers from 10 to 50:
 [11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [22]:
matrix_3x3 = np.arange(9).reshape(3, 3)

In [23]:
print("3x3 Matrix with values from 0 to 8:\n", matrix_3x3)

3x3 Matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [24]:
identity_matrix = np.eye(3)

In [25]:
print("\n3x3 Identity Matrix:\n", identity_matrix)


3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use numpy to generate a random number between 0 and 1

In [26]:
random_number = np.random.rand()

In [27]:
print("Random number between 0 and 1:", random_number)

Random number between 0 and 1: 0.9240312068967041


#### Use numpy to generate an array of 25 random numbers sampled from a standard normal distribution

In [29]:
random_array = np.random.randn(25)

In [30]:
print("\nArray of 25 random numbers from standard normal distribution:\n", random_array)


Array of 25 random numbers from standard normal distribution:
 [ 1.08561851  0.44962259  0.3363946   0.78194826 -0.65324498 -1.311195
 -0.11747094  1.0626854  -1.2917048   0.40251078 -0.53976249 -0.06281868
 -0.4229578   0.49500713  1.62152288 -0.5569297   1.05999314  0.23552818
 -0.77938158  0.25058627 -0.10127525 -0.19394934  1.64533185  0.33421904
  0.04971359]


#### Create the following matrix:

In [31]:
matrix = np.linspace(0.01, 1.00, 100).reshape(10, 10)

In [32]:
print("Generated 10x10 Matrix:\n", matrix)

Generated 10x10 Matrix:
 [[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [33]:
linspace_array = np.linspace(0, 1, 20)

In [34]:
print("\nArray of 20 linearly spaced points between 0 and 1:\n", linspace_array)


Array of 20 linearly spaced points between 0 and 1:
 [0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [35]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [36]:
# write your code here
mat[2:,1:]

[[12 13 14 15]
 [17 18 19 20]]


In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [39]:
# write your code here
mat[3,4]

np.int64(20)

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [40]:
# write your code here
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [41]:
# write your code here
mat[4,:]

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [42]:
# write your code here
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [43]:
mat.sum()

np.int64(325)

325

#### Get the standard deviation of the values in mat

In [44]:
mat.std()

np.float64(7.211102550927978)

7.2111025509279782

#### Get the sum of all the columns in mat

In [45]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

array([55, 60, 65, 70, 75])

# Great Job!